# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/generated_*.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    # pubspec.yaml/dependencies で flutter sdk を一番上に書きたいため
    sort_pub_dependencies: false
